### PR TITLE
delete temporary TFiles 

### PR DESCRIPTION
**Pull request by MustafaMustafa**
- delete temporary TFiles. 
- add .gitignore file.

### CODE REVIEW

**Comment by MustafaMustafa** [comment]
@plexoos , @starsdong 
Can you check this pull request?

**Comment by plexoos** [comment]
Looks fine to me! I would probably just create a temporary TFile instead of TFile*/delete. Here is how I solved a similar problem: https://github.com/plexoos/star-sti-tools/blob/master/StiRootIO/PrgOptionProcessor.cxx#L252
If I remember correctly TFile::IsZombie() does a more general check on file then IsOpen()

**Comment by MustafaMustafa** [comment]
That is right, keeping it on the stack would be better. I will make the change.

**Comment by MustafaMustafa** [comment]
I think this is ready to be merged now.

**Comment by plexoos** [comment]
:+1:

**Pull request merged**
