### PR TITLE
Added following data members:

### PR DESCRIPTION
**Pull request by marrbnl**
1. mVpdTacSum - collision start time measured by VPD
2. mTHUBtime[] - collision trigger time recorded in THUB

### CODE REVIEW

**Comment by MustafaMustafa** [comment]
Hi Rongrong, 

These changes look fine to me. One thing, can you use the full path for out of directory includes e.g StEvent/StEnumerations.h instead of StEnumerations.h. The latter will not compile with tools other than cons.

**Comment by marrbnl** [comment]
Hello Mustafa

Thanks for your comments. I can certainly do that. After the fix, shall I submit another pull request?

**Comment by MustafaMustafa** [comment]
Thanks.

As long as the pull request is open any commits will be automatically added
to the request.

**Comment by marrbnl** [comment]
OK, I see. Thanks!

**Comment by marrbnl** [comment]
Hello Mustafa

I have added the path for the header files. I already added one more data member for StPicoMtdTrigger.

**Pull request merged**
