### PR TITLE
Refactor Ji Xu's refMult pull-request rnc-lbl/star-picoDst#57

### PR DESCRIPTION
**Pull request by MustafaMustafa**
Refactor Ji Xu's refMult pull-request rnc-lbl/star-picoDst#57

### CODE REVIEW

**Comment by MustafaMustafa** [comment]
@xuji19891014 
Please review commit 93afbd5.

**Comment by MustafaMustafa** [comment]
@xuji19891014 , 

Please make sure that the definitions I added in the comments are correct, see  93b3865.

**Comment by ccnuxuji** [comment]
The definition is corrected, thanks for making the code clean.

**Comment by MustafaMustafa** [comment]
Thanks for adding the code Ji.

**Pull request merged**
