### PR TITLE
Some clean up and code fixes not affecting the functionality

### PR DESCRIPTION
**Pull request by plexoos**

### CODE REVIEW

**Comment by plexoos** [comment]
Please check if all looks good and merge

**Comment by MustafaMustafa** [comment]
I am fine with all the changes here. I will ask Xin to approve it and check it in CVS.

**Comment by plexoos** [comment]
Cool. You probably want to invite @starsdong in this organization

**Comment by MustafaMustafa** [comment]
I was just looking for his username. Thank you

**Comment by MustafaMustafa** [comment]
Hi Xin (@starsdong), 

Can you review Dmitri's changes before we merge this pull request?

**Comment by starsdong** [comment]
Hi Mustafa and All,

Of course. This is obvious. Please proceed to merge the change. Thanks

/xin

On Mon, Jul 6, 2015 at 8:34 PM, Mustafa Mustafa notifications@github.com
wrote:

> Hi Xin (@starsdong https://github.com/starsdong),
> 
> Can you review Dmitri's changes before we merge this pull request?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rnc-lbl/star-picoDst/pull/1#issuecomment-119062595.

## 

# 

Xin Dong
Nuclear Science Division
Lawrence Berkeley National Lab
MS70R0319, One Cyclotron Road
Berkeley, CA 94720, USA
Tel: +1-510-486-4121

# Email: XDong@lbl.gov

**Comment by MustafaMustafa** [comment]
@plexoos , should we delete the branch?

**Comment by plexoos** [comment]
Sure, let's delete it. Thanks!

**Comment by plexoos** [comment]
As a side note. For such simple changes/cases I usually rebase branches on top of the master one. This way you would just have a straight history without "loops". I just find it easier to follow the history when the number of merges/loops is minimized.

**Comment by MustafaMustafa** [comment]
Hi Dmitri,

Thanks for the suggestion. I will try to do that next time.

--Mustafa

**Comment by MustafaMustafa** [comment]
I am wondering, is it easy to rebase from a fork pull request?

--Mustafa

**Comment by plexoos** [comment]
You can try to rebase changes in your fork and then check if github updates your pull request automatically. I think it can do that. To rebase you obviously need to update your  fork with changes from the upstream first, then rebase locally, then push to your fork. I think github's pull requests follow the tip of the branch so, no matter how you change it the pull request page will update accordingly. I am not 100% sure about this but it is my guess

**Pull request merged**
