### PR TITLE
RP collection

### PR DESCRIPTION
**Pull request by fulek**
Added:

StPicoRpsCollection
rpMode 
mNTofMatchedPTracks - number of TOF matched primary tracks if there is one vertex with TOF matched tracks
mNVerticesTofMatched - number of vertices with TOF matched tracks
some variables for our internal triggerWords and bunch crossing number (spin analysis).
in rpMode I do not cut the event - I saw that there are some vertex cuts but e.g. in elastic events we do not expect any vertices in TPC.
I found that in the MuDst code there is a bug with two methods (lack of const keyword). Because of that, the constructor in StPicoRpsCollection cannot have const parameter: StPicoRpsCollection::StPicoRpsCollection(StMuRpsCollection & ups)

### CODE REVIEW

**Comment by plexoos** [comment]
All new files:

```
StPicoDstMaker/StPicoRpsCollection.cxx
StPicoDstMaker/StPicoRpsCollection.h
StPicoDstMaker/StPicoRpsTrack.cxx
StPicoDstMaker/StPicoRpsTrack.h
StPicoDstMaker/StPicoRpsTrackPoint.cxx
StPicoDstMaker/StPicoRpsTrackPoint.h
```

are straight copies of their corresponding counterparts from https://github.com/star-bnl/star-muDst/tree/master/StMuDSTMaker/COMMON where "mu" was replaced by "pico". You are essentially double the amount of code but provide exactly zero new functionality. This is not a good practice. Since picoDst already depends on muDst you should just reuse the functionality available in muDst. If the naming is such a big issue I suggest you learn about type aliasing in c++11.

Also, consider splitting your changes in separate topic branches. Clearly, the calculation of TOF matched tracks has nothing to do with adding RP info to picoDst

**Comment by fulek** [comment]
The new files are the exact copy of the MuDst classes but by definition MuDst should have some more variables than pico. We wanted to have an independent code for pico because in the future we may want to reduce the volume of the picoDsts and remove some variables. Because of that I have created new files.
TOF matched tracks has a lot with adding RP info to picoDst. Simply both changes are related with UPC analysis.

**Comment by plexoos** [comment]
Looks like we still need to address these issues. 

With rootcint streamers it is possible to have a smaller number of persistent data members in a derived than in the base class. In fact, a data member inherited from a base class will not be processed by rootcint unless it is explicitly appears in the derived class (as with using BaseClass::someVar). This is how you can control what goes into the derived class streamer.

Regarding other changes in the same commit. Take your own argument to the extreme and imagine when we combine all the changes in this repository merely because all of them are related to picoDst. We would reduce the amount of useful information about what has been changed and most importantly why to zero. You can use "git add -e" to split changes into logical chunks.

**Comment by fulek** [comment]
Hi will close this pull request and open the new one with all the suggestions. Thanks.

**Pull request closed without merging**
