### PR TITLE
Addressing concerns with stongly typed enum in StPicoDstMaker

### PR DESCRIPTION
**Pull request by plexoos**
Related to https://github.com/MustafaMustafa/star-picoDst/commit/d883e4fa33c3b7d9e68a1dbfb6d67c7cc5164fe0#commitcomment-19047099

Introduced a couple of convenience methods to hide the ugly access to picoArrays

### CODE REVIEW

**Comment by MustafaMustafa** [comment]
This is of course a solution. However,  I still think that it is adding code complexity that is not needed. If the only use of StPicoArrayType is as an array index then it is more natural to be able to implicitly convert it to an int. Every time one wants to use the StPicoArrayType in the future will have to either cast it or if it is used profusely will need to come up with a set of methods (like the ones we both introduced) to get around the ugliness of long casting and scope resolution operators. 

I am arguing here that we should just scope a plain enum in StPicoArray class as in https://github.com/MustafaMustafa/star-picoDst/blob/picoArrayType2/StPicoDstMaker/StPicoArrays.h
rather than over using language features. 

By the way, if you insist on the strong enum, I would come up with a different name for getPlacement, the name doesn't reveal the functionality.

**Comment by plexoos** [comment]
Thanks for the feedback Mustafa! I understand your concern about the ugly casts needed to convert enum class to int but I don't see in what cases you expect the end user to apply such casts. Didn't you solve that problem by introducing the following public method `TClonesArray* StPicoDst::picoArray(StPicoArrayType type)` ? The ugly cast is done once inside this method and the end users should not be wanting to do the same by hand.

BTW, I think `getPlacement()` can be updated further to accept only one argument, i.e. the type! Because the number of entries in each array can be accessed by the common  method `StPicoDst::numberOfEntries()` that you introduced.

What name variations do you have in mind for the function like getPlacement?

**Comment by MustafaMustafa** [comment]
Hi Dmitri, 

I meat the future pico developer not the end user. I believe developer time is the most precious resource which I choose to conserve it whenever by avoiding unnecessary complexity. Beside, IMHO, I don't think strong enum is the proper design here.

Maybe getArrayPlacement or getPicoArrayPlacement?

**Comment by plexoos** [comment]
I'll leave it to you to decide whether to switch to enum class or not :) I still think that the type casts are already hidden enough so, both the users and future maintainers can use your methods in StPicoDst to avoid them. There is a couple of "arguments" for strong enums:
- It is obviously the type safety. The user would not be able to request an unknown pico array type by using a non-existing index as in `TClonesArray* StPicoDst::picoArray(int idx=555)`
- If a future maintainer decides to switch from array of arrays (i.e. TClonesArray*\* picoArrays) to, say, a `map<StPicoArrayType, TClonesArray*>` the issue with the index type casting will not exist at all.

If you accept the strong enums please feel free to change the name of getPlacement to whatever you think is more appropriate.

**Pull request closed without merging**
